import type { Metadata } from "next";
import PrivuneLegalPage from "@/components/PrivuneLegalPage";

const url = "https://jonnylab.app/privune/privacy";

export const metadata: Metadata = {
  title: "Privune Privacy Policy | JonnyLab",
  description: "How Privune processes photos, OCR results, metadata, and purchase information.",
  alternates: { canonical: url, languages: { en: url, ko: `${url}/ko`, "x-default": url } },
  openGraph: { title: "Privune Privacy Policy | JonnyLab", description: "How Privune processes photos, OCR results, metadata, and purchase information.", url, siteName: "JonnyLab", type: "website", locale: "en_US", alternateLocale: ["ko_KR"] },
  robots: { index: true, follow: true },
};

const sections = [
  { title: "Introduction", content: <p>This Privacy Policy explains how JonnyLab handles information in Privune (“Privune” or the “App”), an iPhone app that helps users identify and redact potentially sensitive details in photos. Privune is designed around on-device processing, review before export, and creation of a separate Safe Copy.</p> },
  { title: "Information Privune Processes", content: <><p>When you select a photo, Privune processes the image, recognized text, candidate sensitive details, redaction regions, and export settings locally on your device to provide the App’s features. This may include phone numbers, email addresses, registration numbers, payment card numbers, bank account numbers, vehicle registration numbers, and addresses visible in the photo.</p><p>This processing does not mean every sensitive item will be detected. Detection is assistive, and you are responsible for reviewing the selected regions before sharing.</p></> },
  { title: "On-Device Photo and OCR Processing", content: <p>OCR, sensitive-detail detection, region review, redaction rendering, and supported metadata sanitization happen on your iPhone. Photos remain on the device during Privune processing. Privune does not upload photos, OCR text, or detected sensitive information to JonnyLab.</p> },
  { title: "Sensitive Information Detection", content: <p>Privune analyzes recognized text and image regions to suggest details that may be sensitive. Suggestions may be incomplete or incorrect because image quality, text layout, language, and other factors affect detection. Privune does not guarantee that it will identify every sensitive item, and it does not replace legal, compliance, security, or professional review.</p> },
  { title: "Original Photos and Safe Copies", content: <><p>Privune never modifies the original photo. After you review and adjust the selected regions, Privune renders a separate Safe Copy with the chosen solid or pixelated redactions.</p><p>You must inspect the regions and the generated Safe Copy before saving or sharing it. Saved Safe Copies remain in your Photos library until you delete them using the tools provided by iOS.</p></> },
  { title: "Metadata Sanitization", content: <p>When creating a Safe Copy, Privune removes supported metadata fields such as location/GPS, camera make and model, capture date, EXIF, TIFF, IPTC, author, comments, and copyright fields where present. Image formats may contain unsupported or proprietary fields, so Privune does not guarantee removal of every possible metadata field in every file.</p> },
  { title: "Temporary Files", content: <p>Privune may create temporary Safe Copy files locally to support previewing, saving, or sharing. These files are cleaned according to the App’s lifecycle and cleanup rules. Operating-system behavior may affect the precise timing of cleanup. A Safe Copy you save to Photos remains there until you delete it.</p> },
  { title: "Purchases and RevenueCat", content: <><p>Apple processes App Store transactions, billing, subscription renewal, cancellation, and refund requests under Apple’s terms and policies. JonnyLab does not receive or store your full payment-card details.</p><p>Privune uses RevenueCat as a purchase and entitlement management service. RevenueCat may process purchase-related identifiers, product and entitlement information, transaction or receipt information, device or operating-system details, and an anonymous app-user identifier according to its own <a href="https://www.revenuecat.com/privacy-policy/" target="_blank" rel="noopener noreferrer">privacy practices</a>. RevenueCat does not receive your photos, OCR text, or detected sensitive details from Privune.</p></> },
  { title: "Information JonnyLab Does Not Collect", content: <p>JonnyLab does not operate a Privune account system or custom backend. Privune does not send JonnyLab your photos, OCR text, detected details, redaction regions, export history, or saved Safe Copies. The App does not persist OCR results or maintain an export history.</p> },
  { title: "Analytics and Tracking", content: <p>Privune does not use advertising SDKs or analytics SDKs. JonnyLab does not use Privune to build advertising profiles or track your activity across other companies’ apps or websites.</p> },
  { title: "Network Access", content: <p>Core photo selection, OCR, detection, review, redaction, and export do not require uploading content to a server. Network access may be used by Apple and RevenueCat for purchase, subscription, entitlement, and restore-purchase operations. Their handling of purchase-related information is governed by their own terms and privacy practices.</p> },
  { title: "Photo Library Permissions", content: <p>Privune requests the Photos access needed for you to select photos and save Safe Copies. You control this permission in iOS Settings and may limit or revoke it. If access is limited or denied, some selection or saving features may not work. Privune uses access only to provide the photo workflow you initiate.</p> },
  { title: "Data Retention", content: <><p>OCR text, detected details, and editing state are used locally for the active workflow and are not retained by JonnyLab. Temporary files are handled as described above. Saved Safe Copies remain in your Photos library until you delete them, and original photos remain under your control.</p><p>Apple and RevenueCat may retain purchase-related information according to their own policies, legal duties, and service requirements.</p></> },
  { title: "Children’s Privacy", content: <p>Privune is not directed to children under 13, and JonnyLab does not knowingly collect personal information from children through a Privune account or backend because neither exists. If you believe a child has sent information directly to JonnyLab through support, contact us so we can review the request.</p> },
  { title: "Security", content: <p>Privune reduces exposure by processing photos locally and avoiding accounts, uploads, analytics, and a custom backend. However, no device, software, or transmission method is absolutely secure. Protect your iPhone, review every Safe Copy, and use care when choosing where to save or share it.</p> },
  { title: "International Users", content: <p>Core photo processing remains on your device. Apple or RevenueCat may process purchase-related information in countries other than your own, subject to their policies and applicable safeguards. Privacy rights may vary by location; contact us with a Privune-specific question or request.</p> },
  { title: "Changes to This Policy", content: <p>We may update this Privacy Policy to reflect changes to Privune, platform requirements, third-party services, or applicable law. We will publish the revised policy at this URL and update the effective date.</p> },
  { title: "Contact", content: <p>For privacy questions or requests about Privune, contact JonnyLab at <a href="mailto:support@jonnylab.app">support@jonnylab.app</a>. Do not send an original photo containing sensitive information unless you independently choose to share a sanitized example.</p> },
];

export default function PrivunePrivacyPage() {
  return <PrivuneLegalPage lang="en" title="Privacy Policy" effectiveDate="Effective: July 23, 2026" alternateHref="/privune/privacy/ko" alternateLabel="한국어로 보기" sections={sections} otherDocumentHref="/privune/terms" otherDocumentLabel="Terms of Use" />;
}
