import type { Metadata } from "next";
import PrivuneLegalPage from "@/components/PrivuneLegalPage";

const url = "https://jonnylab.app/privune/privacy";

export const metadata: Metadata = {
  title: "Privune Privacy Policy | JonnyLab",
  description: "How Privune processes photos, OCR results, metadata, and purchase information.",
  alternates: { canonical: url, languages: { en: url, ko: `${url}/ko`, "x-default": url } },
  openGraph: { title: "Privune Privacy Policy | JonnyLab", description: "How Privune processes photos, OCR results, metadata, and purchase information.", url, siteName: "JonnyLab", type: "website", locale: "en_US", alternateLocale: ["ko_KR"] },
  robots: { index: true, follow: true },
};

const sections = [
  { title: "Introduction", content: <p>This Privacy Policy explains how JonnyLab handles information in Privune (“Privune” or the “App”), a privacy-first Android and iPhone app that helps adults identify and redact potentially sensitive details in photos. Privune is designed around local-only image analysis, review before export, and creation of a separate Safe Copy.</p> },
  { title: "Information Privune Processes", content: <><p>When you select a photo, Privune processes the image, recognized text, candidate sensitive details, redaction regions, and export settings locally on your device to provide the App’s features. This may include phone numbers, email addresses, registration numbers, payment card numbers, bank account numbers, vehicle registration numbers, and addresses visible in the photo.</p><p>This processing does not mean every sensitive item will be detected. Detection is assistive, and you are responsible for reviewing the selected regions before sharing.</p></> },
  { title: "On-Device Photo and OCR Processing", content: <p>OCR, sensitive-detail detection, bounding-box review, redaction rendering, and supported metadata sanitization happen locally on your device. Original photos, Safe Copies, OCR text, sensitive findings, and bounding boxes are never uploaded to Privune or JonnyLab servers.</p> },
  { title: "Sensitive Information Detection", content: <p>Privune analyzes recognized text and image regions to suggest details that may be sensitive. Suggestions may be incomplete or incorrect because image quality, text layout, language, and other factors affect detection. Privune does not guarantee that it will identify every sensitive item, and it does not replace legal, compliance, security, or professional review.</p> },
  { title: "Original Photos and Safe Copies", content: <><p>Privune never modifies or deletes the original photo. After you review and adjust the selected regions, Privune renders a separate Safe Copy with the chosen solid or pixelated redactions.</p><p>Saving or sharing a Safe Copy happens only after your explicit action. You must inspect the regions and generated result before sharing it. Saved Safe Copies remain in your photo library or files until you delete them using your device’s tools.</p></> },
  { title: "Metadata Sanitization", content: <p>When creating a Safe Copy, Privune removes supported metadata fields such as location/GPS, camera make and model, capture date, EXIF, TIFF, IPTC, author, comments, and copyright fields where present. Image formats may contain unsupported or proprietary fields, so Privune does not guarantee removal of every possible metadata field in every file.</p> },
  { title: "Temporary Files", content: <p>Privune may create temporary Safe Copy files locally to support previewing, saving, or sharing. These files are cleaned according to the App’s lifecycle and cleanup rules. Operating-system behavior may affect the precise timing of cleanup. A Safe Copy you save to Photos remains there until you delete it.</p> },
  { title: "Purchases and RevenueCat", content: <><p>The final planned paid version uses Google Play Billing or the App Store, together with RevenueCat, only for purchases and entitlement management. Google or Apple processes store transactions, billing, subscription renewal, cancellation, and refund requests under its terms and policies. JonnyLab does not receive or store your full payment-card details.</p><p>RevenueCat may process an anonymous App User ID, device and operating-system technical information, and purchase, subscription-transaction, or entitlement data for purchase handling, entitlement delivery, fraud prevention, support, and purchase-related analytics according to its own <a href="https://www.revenuecat.com/privacy-policy/" target="_blank" rel="noopener noreferrer">privacy practices</a>. Photos, Safe Copies, OCR text, sensitive findings, and bounding boxes are never sent to RevenueCat.</p></> },
  { title: "Information JonnyLab Does Not Collect", content: <p>Privune has no user account, image-analysis backend, or analysis history by default. It does not send JonnyLab your photos, Safe Copies, OCR text, sensitive findings, bounding boxes, or export history.</p> },
  { title: "Analytics, Advertising, and Tracking", content: <p>Privune has no ads and does not use a general-purpose analytics SDK. RevenueCat’s limited purchase-related analytics are described above. JonnyLab does not use Privune to build advertising profiles or track your activity across other companies’ apps or websites.</p> },
  { title: "Network Access and Security", content: <p>Core photo selection, OCR, detection, review, redaction, and export do not upload content to a server. Google, Apple, and RevenueCat may use network access for purchase, subscription, entitlement, and restore-purchase operations. Network data is encrypted in transit. No device, software, or transmission method can be guaranteed absolutely secure.</p> },
  { title: "Photo Library Permissions", content: <p>Privune requests only the photo access needed for you to select photos and save Safe Copies. You control this permission in your device settings and may limit or revoke it. If access is limited or denied, some selection or saving features may not work. Privune uses access only for the photo workflow you initiate.</p> },
  { title: "Data Retention and Deletion Requests", content: <><p>OCR text, sensitive findings, bounding boxes, and editing state are processed locally for the active workflow and are not retained by JonnyLab. App-local state remains until removed by the App, cleared through device settings, or removed when you delete the App, subject to operating-system behavior. Saved Safe Copies remain in your photo library or files until you delete them manually.</p><p>Google, Apple, RevenueCat, and payment providers may retain purchase records under their own policies and legal obligations. To request deletion of RevenueCat-linked data controlled by Privune or JonnyLab, follow the steps on the <a href="/privune/data-deletion">Privune Data Deletion Request page</a>. We normally complete verified requests within 30 days, except for records retained as required for tax, accounting, fraud prevention, dispute handling, or legal compliance.</p></> },
  { title: "Intended Audience", content: <p>Privune is intended for adults and is not directed to children. The App has no account or image-analysis backend. If you believe a child sent information directly to JonnyLab through support, contact us so we can review and address it.</p> },
  { title: "Security", content: <p>Privune reduces exposure by processing photos locally and avoiding accounts, image uploads, general-purpose analytics, and an image-analysis backend. Protect your device, review every Safe Copy, and use care when choosing where to save or share it.</p> },
  { title: "International Users", content: <p>Core photo processing remains on your device. Google, Apple, or RevenueCat may process purchase-related information in countries other than your own, subject to their policies and applicable safeguards. Privacy rights may vary by location; contact us with a Privune-specific question or request.</p> },
  { title: "Changes to This Policy", content: <p>We may update this Privacy Policy to reflect changes to Privune, platform requirements, third-party services, or applicable law. We will publish the revised policy at this URL and update the effective date.</p> },
  { title: "Contact", content: <p>For privacy questions or requests about Privune, contact JonnyLab at <a href="mailto:support@jonnylab.app">support@jonnylab.app</a>. Do not send an original photo containing sensitive information unless you independently choose to share a sanitized example.</p> },
];

export default function PrivunePrivacyPage() {
  return <PrivuneLegalPage lang="en" title="Privacy Policy" effectiveDate="Effective and last updated: August 18, 2026" alternateHref="/privune/privacy/ko" alternateLabel="한국어로 보기" sections={sections} otherDocumentHref="/privune/terms" otherDocumentLabel="Terms of Use" />;
}
